export const CREATE_APPOINTMENT_REQUEST = "CREATE_APPOINTMENT_REQUEST";
export const CREATE_APPOINTMENT_SUCCESS = "CREATE_APPOINTMENT_SUCCESS";
export const CREATE_APPOINTMENT_FAIL = "CREATE_APPOINTMENT_FAIL";

export const GET_ALL_APPOINTMENTS_REQUEST = "GET_ALL_APPOINTMENTS_REQUEST";
export const GET_ALL_APPOINTMENTS_SUCCESS = "GET_ALL_APPOINTMENTS_SUCCESS";
export const GET_ALL_APPOINTMENTS_FAIL = "GET_ALL_APPOINTMENTS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
