export const GET_DOCTOR_REQUEST = "GET_DOCTOR_REQUEST";
export const GET_DOCTOR_SUCCESS = "GET_DOCTOR_SUCCESS";
export const GET_DOCTOR_FAIL = "GET_DOCTOR_FAIL";

export const GET_ALL_DOCTORS_REQUEST = "GET_ALL_DOCTORS_REQUEST";
export const GET_ALL_DOCTORS_SUCCESS = "GET_ALL_DOCTORS_SUCCESS";
export const GET_ALL_DOCTORS_FAIL = "GET_ALL_DOCTORS_FAIL";

export const UPDATE_DOCTORS_REQUEST = "UPDATE_DOCTORS_REQUEST";
export const UPDATE_DOCTORS_SUCCESS = "UPDATE_DOCTORS_SUCCESS";
export const UPDATE_DOCTORS_FAIL = "UPDATE_DOCTORS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
