export const CREATE_INVENTORY_REQUEST = "CREATE_INVENTORY_REQUEST";
export const CREATE_INVENTORY_SUCCESS = "CREATE_INVENTORY_SUCCESS";
export const CREATE_INVENTORY_FAIL = "CREATE_INVENTORY_FAIL";

export const GET_INVENTORY_REQUEST = "GET_INVENTORY_REQUEST";
export const GET_INVENTORY_SUCCESS = "GET_INVENTORY_SUCCESS";
export const GET_INVENTORY_FAIL = "GET_INVENTORY_FAIL";

export const GET_ALL_INVENTORY_REQUEST = "GET_ALL_INVENTORY_REQUEST";
export const GET_ALL_INVENTORY_SUCCESS = "GET_ALL_INVENTORY_SUCCESS";
export const GET_ALL_INVENTORY_FAIL = "GET_ALL_INVENTORY_FAIL";

export const DELETE_INVENTORY_REQUEST = "DELETE_INVENTORY_REQUEST";
export const DELETE_INVENTORY_SUCCESS = "DELETE_INVENTORY_SUCCESS";
export const DELETE_INVENTORY_FAIL = "DELETE_INVENTORY_FAIL";

export const UPDATE_INVENTORY_REQUEST = "UPDATE_INVENTORY_REQUEST";
export const UPDATE_INVENTORY_SUCCESS = "UPDATE_INVENTORY_SUCCESS";
export const UPDATE_INVENTORY_FAIL = "UPDATE_INVENTORY_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
